[package]
name = "poker-planning"
version = "0.1.0"
authors = ["MoDPhoenix <ivanchenko.b@gmail.com>"]
homepage = "https://pokerplanning.org/"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
